# Generated by Django 3.0.8 on 2020-09-30 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
    ]
