# Generated by Django 3.0.8 on 2020-10-01 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20201001_0246'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
