# Generated by Django 3.0.8 on 2020-10-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_post_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='f',
            field=models.BooleanField(default=False),
        ),
    ]
