# Generated by Django 3.0.8 on 2020-10-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_follow_f'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='f',
        ),
    ]
