# Generated by Django 3.0.8 on 2020-09-04 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200904_0201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
